name       : python-matplotlib-inline
version    : 0.1.2
release    : 1
source     :
    - https://github.com/ipython/matplotlib-inline/archive/refs/tags/0.1.2.tar.gz : 8dd06feab6d2cbaa0c00115f074bf9cc40a862cbc19c6cf1bec8ba08738cccd6
homepage   : https://github.com/ipython/matplotlib-inline
license    : BSD-3-Clause
component  : programming.python
summary    : Inline Matplotlib backend for Jupyter
description: |
    Matplotlib Inline Back-end for IPython and Jupyter.
rundeps    :
    - python-traitlets
build      : |
    %python3_setup
install    : |
    %python3_install
