name       : python-matplotlib-inline
version    : 0.1.6
release    : 4
source     :
    - https://github.com/ipython/matplotlib-inline/archive/refs/tags/0.1.6.tar.gz : 02e2b2cc143327e35af4fbb90703e5364af0beb56a8fa9c3bcab6efb77b9cb64
homepage   : https://github.com/ipython/matplotlib-inline
license    : BSD-3-Clause
component  : programming.python
summary    : Inline Matplotlib backend for Jupyter
description: |
    Matplotlib Inline Back-end for IPython and Jupyter.
rundeps    :
    - python-traitlets
build      : |
    %python3_setup
install    : |
    %python3_install
