name       : python-matplotlib-inline
version    : 0.1.3
release    : 2
source     :
    - https://github.com/ipython/matplotlib-inline/archive/refs/tags/0.1.3.tar.gz : ac0f859df39b7834c7c2b1e7b8da2124b9517099b4122727131f33f9a8494233
homepage   : https://github.com/ipython/matplotlib-inline
license    : BSD-3-Clause
component  : programming.python
summary    : Inline Matplotlib backend for Jupyter
description: |
    Matplotlib Inline Back-end for IPython and Jupyter.
rundeps    :
    - python-traitlets
build      : |
    %python3_setup
install    : |
    %python3_install
